---
title: "Geometric Classes"
type: "challenge"
description: "Create Ruby objects for different shapes."
visibility: "onsite"
ignore:
- "geometric-classes.md"
- ".rspec"
- "Gemfile"
- "Gemfile.lock"
- "Rakefile"
